logging:
  level:
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.security: DEBUG

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <Google Client ID>
            client-secret: <Google Client Secret>
            scope:
              - email
              - profile
          github:
            client-id: <Github Client ID>
            client-secret: <Github Client Secret>
          facebook:
            client-id: <Facebook Client ID>
            client-secret: <Facebook Client Secret>